[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect правила (опционально)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

